source 'https://rubygems.org'

ruby '3.3.3'

gem 'bundler'
gem 'eventmachine', platforms: [:ruby]
gem 'feedjira'
gem 'htmlbeautifier'
gem 'httparty'
gem 'license_finder'
gem 'nokogiri'
gem 'observer'
gem 'puma'
gem 'rack'
gem 'rack-protection'
gem 'rack-test'
gem 'rackup'
gem 'rake'
gem 'readapt'
gem 'rubocop'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-contrib'
